### ISSUE TITLE
Code generated to a wrong directory 

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.domains#19]
https://github.com/eclipse/lyo.domains/tree/master/oslc-domains/org/eclipse/lyo/oslc/domains

Not under src!

**Comment by jadelkhoury** [comment]
Yes, this is a problem. I need to introduce a "genSettings" for the Vocabulary, the same way we have one for a Specification and/or DomainSpecification.
But note that for Vocabulary, I will only support it at the total Vocabulary level, and not for the specific vocabularies. 

Note also that these same files also exists under https://github.com/eclipse/lyo.domains/tree/master/oslc-domains/src/main/java/org/eclipse/lyo/oslc/domains

So the workaround? delete the folder https://github.com/eclipse/lyo.domains/tree/master/oslc-domains/org/eclipse/lyo/oslc/domains, before you commit it :-)

**Comment by berezovskyi** [comment]
I see.

Any chance you can remove and gitignore these files next time you update domains, please?

--
/Andrew
(from phone)

On 14 Apr 2020, at 16:07, Jad El-khoury <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, this is a problem. I need to introduce a "genSettings" for the Vocabulary, the same way we have one for a Specification and/or DomainSpecification.
But note that for Vocabulary, I will only support it at the total Vocabulary level, and not for the specific vocabularies.

Note also that these same files also exists under https://github.com/eclipse/lyo.domains/tree/master/oslc-domains/src/main/java/org/eclipse/lyo/oslc/domains

So the workaround? delete the folder https://github.com/eclipse/lyo.domains/tree/master/oslc-domains/org/eclipse/lyo/oslc/domains, before you commit it :-)

**Comment by jadelkhoury** [comment]
removed. But I won't gitignore! We should just avoid committing these files until the bug is fixed.
I need the pain of seeing these files in the git interface, otherwise problem will not be fixed.

**Comment by berezovskyi** [comment]
Sounds reasonable!
