### ISSUE TITLE
generate the domain classes from the domains model

### ISSUE THREAD

**Issue by jadelkhoury** [eclipse/lyo.domains#2]
Parrallel to the domains model, generate the JAVA classes for each of the domains in the model.

Should it be: 
* 1 maven project per domain
* 1 maven project, with a package "org.eclipse.lyo.domains.[rm/qm/etc]" for each domain.
* Other?

**Comment by berezovskyi** [comment]
If we stick to OSLC domains only, I think one project can cover them all under separately package names.

How do you want to deal with dcterms &c?

–Andrew.
(sent from my phone)

**Comment by jadelkhoury** [comment]
Good. It would make sense then to put Foaf & dcterms under another (singel) repo.
This would be a good test to see if the generetor produces the right stuff in the right place 😨

**Comment by jadelkhoury** [comment]
solved in https://github.com/eclipse/lyo.domains/pull/3
