### ISSUE TITLE
Set up the build config

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.domains#4]
Set up a Jenkins configuration.

**Comment by jadelkhoury** [comment]
Just to be sure, we don't need to automate the process of producing the java projects from the Designer model.
We just need to build the "oslc-domains" maven project.

and do we need change the version of the project from the current 0.0.1-SNAPSHOT to be 2.4.0?

**Comment by berezovskyi** [comment]
Updated to 4.0.0-SNAPSHOT and added a build config https://ci.eclipse.org/lyo/view/1Enabled/job/lyo-domains-master/5/
